// not protected from including more than once
// this file is included when inspect.h is included
// it is ALSO included when inspect.cpp is compiled
// Please define INSPECTSOURCE when compiling Inspect Library
// Please DO NOT define INSPECTSOURCE when USING library

#ifndef INSPECTSOURCE
// include error typedef for Inspect.h header
	typedef enum errs
	{
		OK,
		FAIL,
		SKIP,
		VIRTUALERROR,
		BADDATATYPE,
		IMAGENOTFOUND,
		IMAGESMUSTBEPNG,
		FILEPROBLEM,
		ALIGNFAILURE,
		ALIGNTRANSFORMNOTFOUND,
		NOTILESUNDEREMASK,
		UNABLETOPALETTIZE,
		UNSUPPORTEDIMAGETYPE,
		UNABLETOINVERTCOVAR,
		PARALLEL_FOR_EXTRACT,
		PARALLEL_FOR_TRAIN,
		PARALLEL_FOR_INSPECT,
		TOO_MANY_INSPECTIONS,
		TILESHAPENOTSUPPORTED,
		LASTERR
	} ERR_INSP;
#else
// include global array of strings for each error
string errorString[] =
{
	"OK",
	"FAIL",
	"SKIP",
	"VIRTUALERROR",
	"BADDATATYPE",
	"IMAGENOTFOUND",
	"IMAGESMUSTBEPNG",
	"FILEPROBLEM",
	"ALIGNFAILURE",
	"ALIGNTRANSFORMNOTFOUND",
	"NOTILESUNDEREMASK",
	"UNABLETOPALETTIZE",
	"UNSUPPORTEDIMAGETYPE",
	"UNABLETOINVERTCOVAR",
	"PARALLEL_FOR_EXTRACT",
	"PARALLEL_FOR_TRAIN",
	"PARALLEL_FOR_INSPECT",
	"TOO_MANY_INSPECTIONS",
	"TILESHAPENOTSUPPORTED",
	"LASTERR"
};
#endif
